name: control-vae
dependencies:
  - python=3.8
  - pyyaml
  - mpi4py
  - numpy
  - scipy
  - cython<=0.29.256
  - cmake>=3.15.0
  - torchvision
  - numba
  - psutil
  - opt_einsum
  - tensorboardx
  - setuptools>=58.2.0